sudo: false

language: node_js
node_js:
    - "16"

branches:
  only:
    - main

before_script:
  - npm install

script:
  - htmlhint index.html
  - jshint javascripts/**/*.{js,json}
  - csslint **/*.css
  - mocha javascripts/tests/*.js
  - node_modules/.bin/jsoncs javascripts/data/events.json